# Site settings
title: TAPS Orlando
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Host a Party |  Member Rewards |  Investment Opportunities |  Employment Application
baseurl: "/taps" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
