# Site settings
title: TAPS Orlando
email: greattaste@tapsorlando.com
description: > # this means to ignore newlines until "baseurl:"
 Host a Party |  Member Rewards |  Investment Opportunities |  Employment Application
baseurl: "/taps" # the subpath of your site, e.g. /blog/
url: "http://tapsorlando.com" # the base hostname & protocol for your site
twitter_username: Taps_WinterPark
facebook_username: TAPSWinterPark

# Build settings
markdown: kramdown
